name: publish to nuget
on:
  push:
    branches:
      - master # Default release branch
jobs:
  publish:
    name: list on nuget
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: publish EasyAbp.Abp.Aliyun.Common.dll
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/EasyAbp.Abp.Aliyun.Common/EasyAbp.Abp.Aliyun.Common.csproj
          VERSION_FILE_PATH: common.props
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      - name: publish EasyAbp.Abp.Aliyun.LiveVideo.dll
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/EasyAbp.Abp.Aliyun.LiveVideo/EasyAbp.Abp.Aliyun.LiveVideo.csproj
          VERSION_FILE_PATH: common.props
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      - name: publish EasyAbp.Abp.Aliyun.Sms.dll
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/EasyAbp.Abp.Aliyun.Sms/EasyAbp.Abp.Aliyun.Sms.csproj
          VERSION_FILE_PATH: common.props
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
